### ISSUE TITLE
test

### ISSUE THREAD

**Issue by asnoppy** [IEDMS/BNT-SM#1]
issue test~

**Comment by ybergner** [comment]
I got this.

Yoav.

**Comment by yanboxu** [comment]
:) 

I closed it~

Yanbo

**Comment by ybergner** [comment]
no worries, I get bug/update emails all the time from other repos.  This is part of what's good about github.
I think you can turn off notifications at various levels, or you can filter them out locally.

**Comment by yanboxu** [comment]
got it!
